# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-12-16 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20201216_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-added_at']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='added_ad',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='added_ad',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
